### ISSUE TITLE
Can't build. Trying to find nodesass.js within my source folder?

### ISSUE THREAD

**Issue by Nic128** [stealjs/steal-sass#5]
Tried installing with  iojs 3 / npm 2, and node 4 / npm 3. If I try to import a .scss file within my donejs project, this happens when trying to build.

```
Error loading "test@0.0.0#styles.scss!steal-sass@1.0.1#main" from "test@0.0.0#index.stache!done-autorender@0.6.0-pre.0#autorender" at file:/home/nmartel/repos/dev/test/src/index.stache
Error loading "nodesass" at file:/home/nmartel/repos/dev/test/nodesass.js
Error loading "nodesass" from "steal-sass@1.0.1#main" at file:/home/nmartel/repos/dev/test/node_modules/steal-sass/main.js
ENOENT: no such file or directory, open '/home/nmartel/repos/dev/test/nodesass.js'
    at Error (native
```

Is there something to configure with steal-tools?

**Comment by justinbmeyer** [comment]
Which version of steal-tools?

**Comment by Nic128** [comment]
0.13.0-pre.3. Here's my package.json dependencies. This is from a fresh donejs init.

```
"dependencies": {
    "can": "^2.3.7",
    "can-connect": "^0.3.3",
    "can-ssr": "^0.11.0-pre.4",
    "done-autorender": "^0.6.0-pre.0",
    "done-component": "^0.4.0-pre.3",
    "done-css": "^1.1.15",
    "generator-donejs": "^0.3.5",
    "jquery": "^2.1.4",
    "steal": "^0.13.0-pre.7",
    "steal-sass": "^1.0.1"
  },
  "devDependencies": {
    "can-fixture": "^0.1.1",
    "documentjs": "^0.3.3",
    "donejs-cli": "^0.6.0-pre.4",
    "donejs-deploy": "^0.3.1",
    "funcunit": "^3.0.0",
    "steal-qunit": "^0.1.1",
    "steal-tools": "^0.13.0-pre.3",
    "testee": "^0.2.3"
  }
```

**Comment by pYr0x** [comment]
same problem here. the build without sass and with less is working.

configuration:
- vagrant linux box
- nodejs 0.12.9 
- globaly installed steal-tools on the vagrant machine
- steal-sass localy installed (within the windows machine)

here the **package.json**

```
{
  "name": "wecanjs",
  "version": "1.0.0",
  "description": "sample app",
  "main": "index.js",
  "dependencies": {
    "can": "^2.3.8",
    "can-connect": "^0.3.3",
    "done-autorender": "^0.5.0",
    "done-component": "^0.3.1",
    "jquery": "^2.1.4",
    "steal": "^0.13.0"
  },
  "devDependencies": {
    "funcunit": "^3.0.0",
    "steal-sass": "^1.0.1",
    "steal-qunit": "^0.1.1"
  },
  "system": {
    "directories": {
      "lib": "src"
    },
    "npmIgnore": [
      "documentjs",
      "gulp",
      "gulp-livereaload",
      "gulp-util",
      "http-server",
      "yo",
      "generator-donejs"
    ]
  },
  "scripts": {
    "build": "node build.js"
  },
  "keywords": [
    "canjs"
  ],
  "author": "Julian Kern",
  "license": "ISC"
}
```

and the **build.js**

```
var stealTools = require("steal-tools");

stealTools.build({
    main: "wecanjs/my/comp/",
    config: __dirname + "/package.json!npm",
    bundlesPath: __dirname + "/javascript/dist"
}, {
    minify: false,
    bundleSteal: false,
    bundleAssets: false
});
```

the error:

```
vagrant@donejs:~/wecanjs$ node build.js
OPENING: wecanjs/my/comp/
Potentially unhandled rejection [7] Error: Error loading "wecanjs@1.0.0#my/comp/comp.scss!steal-sass@1.0.1#main" at <unknown>
Error loading "wecanjs@1.0.0#my/comp/comp.scss!steal-sass@1.0.1#main" from "wecanjs@1.0.0#my/comp/comp" at file:/home/vagrant/wecanjs/src/my/comp/comp.js
Error loading "nodesass" at file:/home/vagrant/wecanjs/nodesass.js
Error loading "nodesass" from "steal-sass@1.0.1#main" at file:/home/vagrant/wecanjs/node_modules/steal-sass/main.js
ENOENT, open '/home/vagrant/wecanjs/nodesass.js'
    at Error (native)
vagrant@donejs:~/wecanjs$ 
```

**Comment by justinbmeyer** [comment]
Why is steal-tools globally installed?

**Comment by pYr0x** [comment]
because i using vagrant and steal-tools uses symlinks or a depencency

**Comment by justinbmeyer** [comment]
what does it use symlinks for?

**Comment by justinbmeyer** [comment]
I think only symlinks are used for the `bin` executables.  you can use steal-tools without that in your own build script.

**Comment by pYr0x** [comment]
can't install steal-tools locally (in my project folder) on the vagrant box.

get an error:

```
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "steal-tools"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! path ../rimraf/bin.js
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../rimraf/bin.js'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "steal-tools"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! path npm-debug.log.2c37269009e803742bc21afcd75862fe
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.2c37269009e803742bc21afcd75862fe'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/wecanjs/npm-debug.log
```

**Comment by Nic128** [comment]
Now I'm getting this error related to sass.js.

```
/home/nmartel/repos/dev/donejs-office-map/node_modules/steal-sass/node_modules/sass.js/dist/sass.sync.js:98
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__sub_I_sass2scss_cpp=Module["__GLOBAL__sub_I_sass2scss_cpp"]=asm["__GLOBAL__sub_I_sass2scss_cpp"];var __GLOBAL__sub_I_color_maps_cpp=Module["__GLOBAL__sub_I_color_maps_cpp"]=asm["__GLOBAL__sub_I_color_maps_cpp"];var __GLOBAL__sub_I_remove_placeholders_cpp=Module["__GLOBAL__sub_I_remove_placeholders_cpp"]=asm["__GLOBAL__sub_I_remove_placeholders_cpp"];var __GLOBAL__sub_I_to_string_cpp=Module["__GLOBAL__sub_I_to_string_cpp"]=asm["__GLOBAL__sub_I_to_string_cpp"];var __GLOBAL__sub_I_memory_manager_cpp=Module["__GLOBAL__sub_I_memory_manager_cpp"]=asm["__GLOBAL__sub_I_memory_manager_cpp"];var _bitshift64Lshr=Module["_bitshift64Lshr"]=asm["_bitshift64Lshr"];var __GLOBAL__sub_I_eval_cpp=Module["__GLOBAL__sub_I_eval_cpp"]=asm["__GLOBAL__sub_I_eval_cpp"];var __GLOBAL__sub_I_node_cpp=Module["__GLOBAL__sub_I_node_cpp"]=asm["__GLOBAL__sub_I_node_cpp"];
could not load memory initializer /home/nmartel/repos/dev/donejs-office-map/node_modules/steal-sass/node_modules/sass.js/dist/libsass.js.mem
```

**Comment by pYr0x** [comment]
@Nic128 is this path /home/nmartel/repos/dev/donejs-office-map/node_modules/steal-sass/node_modules/sass.js/dist/libsass.js.mem correct?

**Comment by Nic128** [comment]
Yes, it's correct. I'm wondering if it's node version related, or donejs related. Using node 4.2.4 / npm 2.14. Donejs 0.6.0. Same error happens with an install of npm3.

Full stack trace:

```
/home/nmartel/repos/dev/donejs-office-map/node_modules/steal-sass/node_modules/sass.js/dist/sass.sync.js:98
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__sub_I_sass2scss_cpp=Module["__GLOBAL__sub_I_sass2scss_cpp"]=asm["__GLOBAL__sub_I_sass2scss_cpp"];var __GLOBAL__sub_I_color_maps_cpp=Module["__GLOBAL__sub_I_color_maps_cpp"]=asm["__GLOBAL__sub_I_color_maps_cpp"];var __GLOBAL__sub_I_remove_placeholders_cpp=Module["__GLOBAL__sub_I_remove_placeholders_cpp"]=asm["__GLOBAL__sub_I_remove_placeholders_cpp"];var __GLOBAL__sub_I_to_string_cpp=Module["__GLOBAL__sub_I_to_string_cpp"]=asm["__GLOBAL__sub_I_to_string_cpp"];var __GLOBAL__sub_I_memory_manager_cpp=Module["__GLOBAL__sub_I_memory_manager_cpp"]=asm["__GLOBAL__sub_I_memory_manager_cpp"];var _bitshift64Lshr=Module["_bitshift64Lshr"]=asm["_bitshift64Lshr"];var __GLOBAL__sub_I_eval_cpp=Module["__GLOBAL__sub_I_eval_cpp"]=asm["__GLOBAL__sub_I_eval_cpp"];var __GLOBAL__sub_I_node_cpp=Module["__GLOBAL__sub_I_node_cpp"]=asm["__GLOBAL__sub_I_node_cpp"];
could not load memory initializer /home/nmartel/repos/dev/donejs-office-map/node_modules/steal-sass/node_modules/sass.js/dist/libsass.js.mem

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "develop"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! donejs-office-map@0.0.0 develop: `can-serve --develop --port 8080`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the donejs-office-map@0.0.0 develop script 'can-serve --develop --port 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the donejs-office-map package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     can-serve --develop --port 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs donejs-office-map
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls donejs-office-map
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nmartel/repos/dev/donejs-office-map/npm-debug.log
Error: Command `npm` did not complete successfully
    at ChildProcess.<anonymous> (/home/nmartel/repos/dev/donejs-office-map/node_modules/donejs-cli/lib/utils.js:37:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Nic128** [comment]
Missed this detail.

Running `npm run build` is working. But not `npm run develop`.

**Comment by Lighttree** [comment]
Hi, is there any updates regarding this issue ?
I have this issue just after generating new project by 'donejs init' and installing steal-sass.

Log:

```
> client-config-app@0.0.0 develop /Users/Lighttree/Development/client-config-app
> can-serve --develop --port 8080

can-serve starting on http://localhost:8080
Potentially unhandled rejection [6] Error: Error loading "client-config-app@0.0.0#styles.scss!steal-sass@1.0.1#main" at <unknown>
Error loading "client-config-app@0.0.0#styles.scss!steal-sass@1.0.1#main" from "client-config-app@0.0.0#index.stache!done-autorender@0.6.0#autore
nder" at file:/Users/Lighttree/Development/client-config-app/src/index.stache
Error loading "nodesass" at file:/Users/Lighttree/Development/client-config-app/nodesass.js
Error loading "nodesass" from "steal-sass@1.0.1#main" at file:/Users/Lighttree/Development/client-config-app/node_modules/steal-sass/main.js

ENOENT, open '/Users/Lighttree/Development/client-config-app/nodesass.js'
    at Error (native)
Potentially unhandled rejection [7] Error: Error loading "client-config-app@0.0.0#styles.scss!steal-sass@1.0.1#main" at <unknown>
Error loading "client-config-app@0.0.0#styles.scss!steal-sass@1.0.1#main" from "client-config-app@0.0.0#index.stache!done-autorender@0.6.0#autore
nder" at file:/Users/Lighttree/Development/client-config-app/src/index.stache
Error loading "nodesass" at file:/Users/Lighttree/Development/client-config-app/nodesass.js
Error loading "nodesass" from "steal-sass@1.0.1#main" at file:/Users/Lighttree/Development/client-config-app/node_modules/steal-sass/main.js
ENOENT, open '/Users/Lighttree/Development/client-config-app/nodesass.js'
    at Error (native)
```

package.json

```
{
  "name": "client-config-app",
  "version": "0.0.0",
  "description": "",
  "homepage": "",
  "author": {
    "name": "",
    "email": "",
    "url": ""
  },
  "scripts": {
    "test": "testee src/test.html --browsers firefox --reporter Spec",
    "start": "can-serve --port 8080",
    "develop": "can-serve --develop --port 8080",
    "document": "documentjs",
    "build": "node build"
  },
  "main": "client-config-app/index.stache!done-autorender",
  "files": [
    "src"
  ],
  "keywords": [],
  "system": {
    "main": "client-config-app/index.stache!done-autorender",
    "directories": {
      "lib": "src"
    },
    "configDependencies": [
      "live-reload"
    ],
    "npmIgnore": [
      "documentjs",
      "testee",
      "donejs-deploy",
      "generator-donejs",
      "donejs-cli"
    ]
  },
  "dependencies": {
    "can": "^2.3.0",
    "can-connect": "^0.3.0",
    "can-ssr": "^0.11.0",
    "done-autorender": "^0.6.0",
    "done-component": "^0.4.0",
    "done-css": "~1.1.13",
    "generator-donejs": "^0.4.3",
    "jquery": "2.1.4",
    "steal": "^0.13.0",
    "steal-sass": "^1.0.1"
  },
  "devDependencies": {
    "documentjs": "^0.4.1",
    "donejs-deploy": "^0.4.0",
    "funcunit": "~3.0.0",
    "steal-qunit": "^0.1.1",
    "steal-tools": "^0.13.0",
    "testee": "^0.2.4",
    "donejs-cli": "^0.6.0",
    "can-fixture": "^0.1.0"
  }
}
```

Maybe someone have ideas ?

**Comment by pYr0x** [comment]
@Lighttree there is a fix in the current master branch. unfortunately this is not tagged as a verion, so npm is taken the wrong version
maybe @matthewp  can update to the next version so it will be available in npm

**Comment by pYr0x** [comment]
@Lighttree @Nic128 should now work, please update steal-sass.

reopen that issue if it is not working
